---
  ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'
  ansible_ssh_private_key_file: "../bootstrap_cfg/id_ed25519"
  ansible_paramiko_host_key_checking: false
  ansible_python_interpreter: "/usr/local/bin/python3"